apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
  labels:
    app.kubernetes.io/part-of: demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: demo
    spec:
      containers:
      - image: masanara/utils:0.4
        name: workload
        securityContext:
          runAsUser: 0
        resources: {}
