apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: demo
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: demo
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
    node
  selector:
    app.kubernetes.io/part-of: demo
  type: NodePort
