apiVersion: v1
kind: Namespace
metadata:
  name: eo-demo
  labels:
    name: eo-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: eo-demo
  name: eo-demo
  namespace: eo-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/part-of: eo-demo
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: eo-demo
  namespace: eo-demo
spec:
  to:
    kind: Service
    name: eo-demo
  port:
    targetPort: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
  namespace: eo-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: eo-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eo-demo
  namespace: eo-demo
  labels:
    app.kubernetes.io/part-of: eo-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: eo-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: eo-demo
    spec:
      containers:
      - image: masanara/demoapp:1.1
        name: workload
