apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: edge-inferencing-events
  namespace: peoplecount
spec:
  replicas: 1
  service:
    type: NodePort
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_stream
  persistence:
    storageClassName: topolvm-provisioner
