apiVersion: v1
kind: Namespace
metadata:
  name: eo-demo
  labels:
    name: eo-demo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: eo-demo
  name: eo-demo
  namespace: eo-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/part-of: eo-demo
  type: LoadBalancer
  loadBalancerIP: 192.168.0.220
