apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dobot-control
  name: dobot-control
  namespace: dobot-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dobot-control
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dobot-control
    spec:
      containers:
      - image: masanara/dobot-control:y
        name: dobot-control
        terminationGracePeriodSeconds: 0
